# Uncomment the next line to define a global platform for your project
#source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.15'

target 'CrossShare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CrossShare

  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'Sparkle'
  pod 'RealmSwift'
end
