package unixSocket

const (
	UNIX_SOCKET_TYPE_REQUEST  = 0
	UNIX_SOCKET_TYPE_RESPONSE = 1
	UNIX_SOCKET_TYPE_NOTIFY   = 2
	UNIX_SOCKET_TYPE_MAX      = 3
)

const (
	UNIX_SOCKET_CODE_RESERVED           = 0
	UNIX_SOCKET_CODE_AUTH_DEVICE        = 1
	UNIX_SOCKET_CODE_UPDATE_DEVICE_NAME = 2
	UNIX_SOCKET_CODE_UPDATE_MOUSE_POS   = 3
	UNIX_SOCKET_CODE_DRAG_FILE_START    = 4
	UNIX_SOCKET_CODE_DRAG_FILE_END      = 5
	UNIX_SOCKET_CODE_GET_DIAS_ID        = 6
	UNIX_SOCKET_CODE_MAX                = 7
)

const (
	UNIX_SOCKET_HEADER_LEN_POS                   = 11
	UNIX_SOCKET_HEADER_LEN_SIZE                  = 4
	UNIX_SOCKET_CONTENT_LEN_AUTH_DEVICE_REQ      = 3
	UNIX_SOCKET_CONTENT_LEN_AUTH_DEVICE_RESP     = 1
	UNIX_SOCKET_CONTENT_LEN_UPDATE_MOUSE_POS_REQ = 8
)

var (
	kHeader = [5]byte{'R', 'T', 'K', 'C', 'S'}
)
