/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 6 "main.go"

#include <stdlib.h>
#include <stdint.h>

typedef void (*CallbackPasteXClipData)(char* text,char* image,char* html);
typedef void (*CallbackUpdateClientStatus)(char* clientJsonStr);
typedef void (*CallbackMethodFileListNotify)(char* ip, char* id, char* platform,unsigned int fileCnt, unsigned long long totalSize,unsigned long long timestamp, char* firstFileName, unsigned long long firstFileSize);
typedef void (*CallbackUpdateMultipleProgressBar)(char* ip,char* id, char* deviceName, char* currentfileName,unsigned int recvFileCnt, unsigned int totalFileCnt,unsigned long long currentFileSize,unsigned long long totalSize,unsigned long long recvSize,unsigned long long timestamp);
typedef void (*CallbackMethodStartBrowseMdns)(char* instance, char* serviceType);
typedef void (*CallbackMethodStopBrowseMdns)();
typedef char* (*CallbackAuthData)();
typedef void (*CallbackSetDIASStatus)(unsigned int status);
typedef void (*CallbackSetMonitorName)(char* monitorName);
typedef void (*CallbackRequestUpdateClientVersion)(char* clientVer);
typedef void (*CallbackNotifyErrEvent)(char* id, unsigned int errCode, char* arg1, char* arg2, char* arg3, char* arg4);
typedef void (*CallbackNotifyBrowseResult)(char* monitorName, char* instance, char* ip, char* version, unsigned long long timestamp);

static CallbackPasteXClipData gCallbackPasteXClipData = 0;
static CallbackUpdateClientStatus gCallbackUpdateClientStatus = 0;
static CallbackMethodFileListNotify gCallbackMethodFileListNotify = 0;
static CallbackUpdateMultipleProgressBar gCallbackUpdateMultipleProgressBar = 0;
static CallbackMethodStartBrowseMdns gCallbackMethodStartBrowseMdns = 0;
static CallbackMethodStopBrowseMdns gCallbackMethodStopBrowseMdns = 0;
static CallbackAuthData gCallbackAuthData = 0;
static CallbackSetDIASStatus gCallbackSetDIASStatus = 0;
static CallbackSetMonitorName gCallbackSetMonitorName = 0;
static CallbackRequestUpdateClientVersion gCallbackRequestUpdateClientVersion = 0;
static CallbackNotifyErrEvent gCallbackNotifyErrEvent = 0;
static CallbackNotifyBrowseResult gCallbackNotifyBrowseResult = 0;


static void setCallbackPasteXClipData(CallbackPasteXClipData cb) {gCallbackPasteXClipData = cb;}
static void invokeCallbackPasteXClipData(char* text,char* image,char* html) {
	if (gCallbackPasteXClipData) {gCallbackPasteXClipData(text, image, html);}
}
static void setCallbackUpdateClientStatus(CallbackUpdateClientStatus cb) {gCallbackUpdateClientStatus = cb;}
static void invokeCallbackUpdateClientStatus(char* clientJsonStr) {
	if (gCallbackUpdateClientStatus) {gCallbackUpdateClientStatus(clientJsonStr);}
}
static void setCallbackMethodFileListNotify(CallbackMethodFileListNotify cb) {gCallbackMethodFileListNotify = cb;}
static void invokeCallbackMethodFileListNotify(char* ip, char* id, char* platform,unsigned int fileCnt, unsigned long long totalSize,unsigned long long timestamp, char* firstFileName, unsigned long long firstFileSize) {
	if (gCallbackMethodFileListNotify) {gCallbackMethodFileListNotify(ip, id, platform, fileCnt, totalSize, timestamp, firstFileName, firstFileSize);}
}
static void setCallbackUpdateMultipleProgressBar(CallbackUpdateMultipleProgressBar cb) {gCallbackUpdateMultipleProgressBar = cb;}
static void invokeCallbackUpdateMultipleProgressBar(char* ip,char* id, char* deviceName, char* currentfileName,unsigned int recvFileCnt, unsigned int totalFileCnt,unsigned long long currentFileSize,unsigned long long totalSize,unsigned long long recvSize,unsigned long long timestamp) {
	if (gCallbackUpdateMultipleProgressBar) {gCallbackUpdateMultipleProgressBar(ip,id, deviceName,currentfileName,recvFileCnt,totalFileCnt,currentFileSize,totalSize, recvSize, timestamp);}
}
static void setCallbackMethodStartBrowseMdns(CallbackMethodStartBrowseMdns cb) {gCallbackMethodStartBrowseMdns = cb;}
static void invokeCallbackMethodStartBrowseMdns(char* instance, char* serviceType) {
	if (gCallbackMethodStartBrowseMdns) {gCallbackMethodStartBrowseMdns(instance, serviceType);}
}
static void setCallbackMethodStopBrowseMdns(CallbackMethodStopBrowseMdns cb) {gCallbackMethodStopBrowseMdns = cb;}
static void invokeCallbackMethodStopBrowseMdns() {
	if (gCallbackMethodStopBrowseMdns) {gCallbackMethodStopBrowseMdns();}
}
static void setCallbackGetAuthData(CallbackAuthData cb) {gCallbackAuthData = cb;}
static char* invokeCallbackGetAuthData() {
	if (gCallbackAuthData) { return gCallbackAuthData();}
    return NULL;
}
static void setCallbackSetDIASStatus(CallbackSetDIASStatus cb) {gCallbackSetDIASStatus = cb;}
static void invokeCallbackSetDIASStatus(unsigned int status) {
	if (gCallbackSetDIASStatus) { gCallbackSetDIASStatus(status);}
}
static void setCallbackSetMonitorName(CallbackSetMonitorName cb) {gCallbackSetMonitorName = cb;}
static void invokeCallbackSetMonitorName(char* monitorName) {
	if (gCallbackSetMonitorName) { gCallbackSetMonitorName(monitorName);}
}
static void setCallbackRequestUpdateClientVersion(CallbackRequestUpdateClientVersion cb) {gCallbackRequestUpdateClientVersion = cb;}
static void invokeCallbackRequestUpdateClientVersion(char* clientVer) {
	if (gCallbackRequestUpdateClientVersion) { gCallbackRequestUpdateClientVersion(clientVer);}
}
static void setCallbackNotifyErrEvent(CallbackNotifyErrEvent cb) {gCallbackNotifyErrEvent = cb;}
static void invokeCallbackNotifyErrEvent(char* id, unsigned int errCode, char* arg1, char* arg2, char* arg3, char* arg4) {
	if (gCallbackNotifyErrEvent) { gCallbackNotifyErrEvent(id,errCode,arg1,arg2,arg3,arg4);}
}
static void setCallbackNotifyBrowseResult(CallbackNotifyBrowseResult cb) {gCallbackNotifyBrowseResult = cb;}
static void invokeCallbackNotifyBrowseResult(char* monitorName, char* instance, char* ip, char* version, unsigned long long timestamp) {
	if (gCallbackNotifyBrowseResult) { gCallbackNotifyBrowseResult(monitorName, instance, ip, version, timestamp);}
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void SetCallbackPasteXClipData(CallbackPasteXClipData cb);
extern void SetCallbackUpdateClientStatus(CallbackUpdateClientStatus cb);
extern void SetCallbackMethodFileListNotify(CallbackMethodFileListNotify cb);
extern void SetCallbackUpdateMultipleProgressBar(CallbackUpdateMultipleProgressBar cb);
extern void SetCallbackMethodStartBrowseMdns(CallbackMethodStartBrowseMdns cb);
extern void SetCallbackMethodStopBrowseMdns(CallbackMethodStopBrowseMdns cb);
extern void SetCallbackGetAuthData(CallbackAuthData cb);
extern void SetCallbackDIASStatus(CallbackSetDIASStatus cb);
extern void SetCallbackMonitorName(CallbackSetMonitorName cb);
extern void SetCallbackRequestUpdateClientVersion(CallbackRequestUpdateClientVersion cb);
extern void SetCallbackNotifyErrEvent(CallbackNotifyErrEvent cb);
extern void SetCallbackNotifyBrowseResult(CallbackNotifyBrowseResult cb);
extern void MainInit(GoString deviceName, GoString serverId, GoString serverIpInfo, GoString listenHost, GoInt listenPort);
extern void SetMsgEventFunc(GoInt event, GoString arg1, GoString arg2, GoString arg3, GoString arg4);
extern char* GetClientListEx();
extern char* GetClientList();
extern void SendAddrsFromPlatform(GoString addrsList);
extern void SendNetInterfaces(GoString name, GoString mac, GoInt mtu, GoInt index, GoUint flag);
extern void SendXClipData(GoString text, GoString image, GoString html);
extern GoInt SendMultiFilesDropRequest(GoString multiFilesData);
extern void SetCancelFileTransfer(GoString ipPort, GoString clientID, GoUint64 timeStamp);
extern void SetNetWorkConnected(GoUint8 isConnect);
extern void SetHostListenAddr(GoString listenHost, GoInt listenPort);
extern void SetDIASID(GoString DiasID);
extern void SetDetectPluginEvent(GoUint8 isPlugin);
extern char* GetVersion();
extern char* GetBuildDate();
extern void SetupRootPath(GoString rootPath);
extern void SetBrowseMdnsResult(GoString instance, GoString ip, GoInt port, GoString productName, GoString mName, GoString timestamp, GoString version);
extern void SetConfirmDocumentsAccept(GoUint8 ifConfirm);
extern void FreeCString(char* p);
extern void BrowseLanServer();
extern void WorkerConnectLanServer(GoString instance);

#ifdef __cplusplus
}
#endif
