# platform :ios, '15.6'

target 'CrossShare_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CrossShare_iOS

  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'MBProgressHUD'

  target 'CrossShare_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CrossShare_iOSUITests' do
    # Pods for testing
  end
  
  target 'share' do
    use_frameworks!
    
    pod 'SwiftyJSON'
    pod 'SnapKit'
    pod 'MBProgressHUD'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "15.6"
    end
  end
end
